services:
  x-ui-tg-go:
    image: ghcr.io/d3kause/xui-tg-admin:latest
    container_name: x-ui-tg-go
    restart: unless-stopped
    environment:
      - TG_TOKEN=1234567890:YOUR_BOT_TOKEN_FROM_BOTFATHER
      - TG_ADMIN_IDS=123456789,987654321
      - XRAY_USER=admin
      - XRAY_PASSWORD=your_xui_panel_password
      - XRAY_API_URL=http://localhost:54321/api
      - XRAY_SUB_URL_PREFIX=http://YOUR_SERVER_IP:54321/sub
      - LOG_LEVEL=info
    volumes:
      - ./data:/root/data