services:
  x-ui-tg-go:
    build: .
    container_name: x-ui-tg-go
    restart: unless-stopped
    environment:
      - TG_TOKEN=${TG_TOKEN}
      - TG_ADMIN_IDS=${TG_ADMIN_IDS}
      - XRAY_USER=${XRAY_USER}
      - XRAY_PASSWORD=${XRAY_PASSWORD}
      - XRAY_API_URL=${XRAY_API_URL}
      - XRAY_SUB_URL_PREFIX=${XRAY_SUB_URL_PREFIX}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ./data:/root/data